feed/urls.py
from django.conf.urls import url
from feed.views import hashtags, vote, entry_detail, comment

urlpatterns = [
    url(r'hashtags$', hashtags, name='hashtags'),
    url(r'vote$', vote, name='vote'),
    url(r'comment$', comment, name='comment'),
    url(r'view/(?P<id>\d+)', entry_detail, name='show'),
]

vile/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from feed.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Home page
    url(r'^$', home, name='home'),

    # Page not found
    url(r'^404$', home, name='404'),

    # Module Feed
    url(r'^feed/', include('feed.urls', namespace='feed')),

    # Module person
    url(r'^person/', include('person.urls', namespace='person')),

    # Module Public
    url(r'^club/', include('public.urls', namespace='club')),

    # Module Streaming
    url(r'^pool/', include('stream.urls', namespace='stream')),
]

feed/models.py
from __future__ import unicode_literals
import re
from django.db import models
from vile.service import Votable


class Hashtag(models.Model, Votable):
    name = models.CharField(max_length=32, db_index=True)
    karma = models.IntegerField(db_index=True, default=0, blank=True)

    def __unicode__(self):
        return '#{}'.format(self.name.replace(' ', ''))

    @staticmethod
    def get_or_create(tags_list, filtering=None):
        result = []
        for tag in tags_list:
            tag = unicode(tag.strip().lower().replace(' ', ''))
            try:
                pk = int(tag)
                result.append(Hashtag.objects.get(pk=pk))
            except:
                if len(tag) < 2:
                    continue

                instances = Hashtag.objects.filter(name=tag)
                if instances.count() > 0:
                    for tag in instances:
                        result.append(tag)
                else:
                    tag = Hashtag(name=tag)
                    tag.save()
                    result.append(tag)
        return result if not filtering else map(filtering, result)


class Entry(models.Model, Votable):
    title = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField()

    tags = models.ManyToManyField(Hashtag)
    owner = models.ForeignKey('person.Person')
    publisher = models.ForeignKey('public.Public')

    karma = models.IntegerField(db_index=True, default=0, blank=True)
    created_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    @property
    def comments(self):
        return Comment.objects.filter(target=self).order_by('-id')

    @property
    def comments_count(self):
        return Comment.objects.filter(target=self).count()

    def vote(self, author, positive=True):
        super(Entry, self).vote(author, positive)
        for tag in self.tags.all():
            tag.vote(author=author, positive=positive)
            tag.save()

        return self.publisher.vote(author=author, positive=positive)


class Comment(models.Model, Votable):
    target = models.ForeignKey(Entry)

    content = models.TextField()
    publisher = models.ForeignKey('person.Person')

    karma = models.IntegerField(db_index=True, default=0, blank=True)
    created_at = models.DateTimeField(auto_now=True, blank=True, null=True)

feed/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from feed.models import Comment


class CommentForm(ModelForm):
    def __init__(self, author=None, *args, **kwargs):
        data = kwargs.get('data')
        if author is not None and data:
            data.setlist('publisher', [author.pk])
            kwargs['data'] = data

        super(CommentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Comment
        fields = [
            'target',
            'content',
            'publisher'
        ]

feed/views.py
import json
from feed.forms import CommentForm
from vile.service import RelatedFeeds
from feed import models as feed_models
from person import models as person_models
from public import models as public_models
from public.views import club_homepage
from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponse, redirect


def handle_public_home(request):
    if not request.subdomain:
        return

    public = public_models.Public.objects.filter(slug__iexact=request.subdomain).first()
    if not public:
        return

    return club_homepage(request, public.pk)


def home(request):
    public = handle_public_home(request)
    if public is not None:
        return public

    entries = RelatedFeeds.list(
        search_term=request.GET.get('hash', ''),
        page=request.current_page
    )

    template_name = 'feed/home.html'
    if request.current_page > 1:
        template_name = 'feed/listing.html'

    return render(request, template_name, {
        'hash': request.GET.get('hash', ''),
        'entries': entries,
        'has_next': RelatedFeeds.has_next_page
    })


def entry_detail(request, id):
    try:
        entry = feed_models.Entry.objects.get(pk=id)
    except feed_models.Entry.DoesNotExist:
        return redirect(reverse('404'))

    club = entry.publisher
    is_owner = club.owner_id == request.user.pk
    is_member = club.members.filter(id=request.user.pk).count() > 0
    is_founder = club.founders.filter(id=request.user.pk).count() > 0

    is_subscribed = is_owner or is_member or is_founder

    return render(request, 'feed/entry.html', {
        'entry': entry,
        'club': club,
        'is_owner': is_owner,
        'is_member': is_member,
        'is_founder': is_founder,
        'is_subscribed': is_subscribed
    })


def hashtags(request):
    search_term = request.GET.get('search', '').lower()
    qset = feed_models.Hashtag.objects

    if search_term:
        qset = qset.filter(name__contains=search_term)
    qset = qset.order_by('-karma', 'name')
    return HttpResponse(
        content=json.dumps([{'text': '#' + x.name, 'value': x.pk} for x in qset.all()[:50]]),
        content_type='application/json'
    )


def comment(request):
    if request.method != 'POST':
        return HttpResponse(content='', content_type='text/html')

    form = CommentForm(author=request.user, data=request.POST.copy())
    if form.is_valid():
        form.save()
        return render(request, 'feed/comment_detail.html', {
            'comment': form.instance
        })

    return HttpResponse(content_type='text/html')


def vote(request):
    if request.method != 'POST':
        return HttpResponse(content='-', content_type='text/plain')

    available = [
        feed_models,
        person_models,
        public_models
    ]

    target = request.POST.get('to', '.').split('.')
    target_model = target[0]
    target_pk = target[1]

    positive = int(request.POST.get('positive', '1')) > 0

    model_instance = None
    for mdl in available:
        if hasattr(mdl, target_model):
            model_instance = getattr(mdl, target_model)
        break

    if model_instance is None:
        return HttpResponse(content='-', content_type='text/plain')

    try:
        instance = model_instance.objects.get(pk=int(target_pk))
    except:
        return HttpResponse(content='-', content_type='text/plain')

    instance.vote(author=request.user, positive=positive)
    return HttpResponse(content=str(instance.karma), content_type='text/plain')

templates/feed/comment_detail.html
{% load i18n %}
<div class="item block">
    <header>
        <img src="{{ comment.publisher.image }}" alt="{{ comment.publisher.username }}">
        <div class="header">
            <a href="" class="author">
                {{ comment.publisher.username }}
            </a>
            <span class="info">{% trans 'at' %} {{ comment.created_at }}</span>
        </div>
    </header>

    <section class="item-content block">
        {{ comment.content }}
    </section>

    <section class="item-footer">
        {% if user.is_authenticated %}
        <div class="float-rt">
            <span class="btn" onclick="Vote('Comment.{{ comment.pk }}', 0)"><i class="fa fa-thumbs-down"></i></span>
            <span class="karma" data-target="Comment.{{ comment.pk }}">{{ comment.karma }}</span>
            <span class="btn" onclick="Vote('Comment.{{ comment.pk }}', 1)"><i class="fa fa-thumbs-up"></i></span>
        </div>
        {% endif %}

        <div class="block-inline">
            {% if comment.publisher_id == user.id %}
                <a href="">
                    <i class="fa fa-trash"></i>
                </a>
            {% else %}
                &nbsp;
            {% endif %}
        </div>
    </section>
</div>

templates/feed/comment_listing.html
{% load staticfiles %}
{% load content %}
{% load i18n %}

{% for comment in comments %}
    {% include 'feed/comment_detail.html' with comment=comment %}
{% empty %}
    <div class="empty">{% trans 'No comments yet' %}</div>
{% endfor %}

templates/feed/comments_form.html
{% load staticfiles %}
{% load i18n %}

<div class="item block html-form wide">
    <header>
        <img src="{{ club.image }}" alt="{% trans 'Author' %}">
        <div class="header">
            <span class="btn float-rt publish" onclick="Public.comment('.editor', '{{ entry.pk }}')">{% trans 'Publicate' %}</span>
            <span class="author">{{ club.title }}</span>
            <span class="info">{{ user.username }}</span>
        </div>
    </header>
    <section class="item-content input">
        <textarea data-autoresize="24" data-empty class="editor"></textarea>
    </section>
</div>

templates/feed/entry.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra %}
    {% include 'public/header.html' %}
{% endblock extra %}

{% block content %}
    {% include 'feed/entry_detail.html' with is_detail=entry.pk %}

    <!-- Comments form -->
    {% include 'feed/comments_form.html' with form=comment_form entry=entry %}

    <!-- Comments listing -->
    <div data-fresh="comments">
        {% include 'feed/comment_listing.html' with comments=entry.comments.all %}
    </div>
{% endblock content %}

{% block rside %}
    {% include 'public/rside.html' %}
{% endblock rside %}

templates/feed/entry_detail.html
{% load content %}
{% load i18n %}
<div class="item block">
    <header>
        <img src="{{ entry.publisher.image }}" alt="{{ entry.publisher.title }}">
        <div class="header">
            <a href="{% url 'club:home' entry.publisher.pk %}" class="author">
                {{ entry.publisher.title }}
            </a>
            <span class="info">{{ entry.owner.username }} at {{ entry.created_at }}</span>
        </div>
    </header>
    <section class="item-content">
        {{ entry.content|content:is_detail }}
    </section>

    <section class="item-footer">
        {% if user.is_authenticated %}
        <div class="float-rt">
            <span class="btn" onclick="Vote('Entry.{{ entry.pk }}', 1)"><i class="fa fa-thumbs-up"></i></span>
            <span class="karma" data-target="Entry.{{ entry.pk }}">{{ entry.karma }}</span>
            <span class="btn" onclick="Vote('Entry.{{ entry.pk }}', 0)"><i class="fa fa-thumbs-down"></i></span>
        </div>
        {% endif %}

        <div class="block-inline footer">
            {% if entry.publisher.owner_id == user.pk or entry.owner_id == user.pk %}
                <a href="">
                    <i class="fa fa-trash"></i> <span class="sm-hide">{% trans 'Delete' %}</span>
                </a>
            {% endif %}

            <a href="{% url 'feed:show' entry.pk %}">
                <i class="fa fa-comments"></i> <span class="sm-hide">{% trans 'Comments' %}</span> {{ entry.comments_count }}
            </a>
        </div>
    </section>
</div>

templates/feed/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/paginator.js' %}"></script>
    <script type="text/javascript">
        $(function(){
            window.pager = new Paginator('{% url 'home' %}', {
                hash: '{{ hash }}'
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div data-container>
        {% include 'feed/listing.html' %}
    </div>
{% endblock content %}

templates/feed/listing.html
{% load i18n %}
{% for entry in entries %}
    {% include 'feed/entry_detail.html' with entry=entry is_detail=0 %}
{% empty %}
    <div class="empty">{% trans 'No publications found' %}</div>
{% endfor %}
{% if has_next %}
    <a href="javascript:void(0);" class="btn block-block" onclick="pager.load_next(this)">{% trans 'Load more' %}</a>
{% endif %}