feed/urls.py
from django.conf.urls import url
from feed.views import hashtags, vote, entry_detail, comment

urlpatterns = [
    url(r'hashtags$', hashtags, name='hashtags'),
    url(r'vote$', vote, name='vote'),
    url(r'comment$', comment, name='comment'),
    url(r'view/(?P<id>\d+)', entry_detail, name='show'),
]

person/urls.py
from django.conf.urls import url
from person.views import (
    login_page, authorize, out, avatar, profile, register,
    confirmation
)


urlpatterns = [
    url(r'login$', login_page, name='login'),
    url(r'auth$', authorize, name='auth'),
    url(r'exit$', out, name='logout'),
    url(r'avatar$', avatar, name='avatar'),
    url(r'register$', register, name='register'),
    url(r'confirm/(?P<key>.+)$', confirmation, name='confirmation'),
    url(r'(?P<username>.+)$', profile, name='profile')
]

vile/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from feed.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Home page
    url(r'^$', home, name='home'),

    # Page not found
    url(r'^404$', home, name='404'),

    # Module Feed
    url(r'^feed/', include('feed.urls', namespace='feed')),

    # Module person
    url(r'^person/', include('person.urls', namespace='person')),

    # Module Public
    url(r'^club/', include('public.urls', namespace='club')),

    # Module Streaming
    url(r'^pool/', include('stream.urls', namespace='stream')),
]

person/models.py
from __future__ import unicode_literals
from cleave.encrypt import Encrypt
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from vile.service import Votable
from django.templatetags.static import static
from django.utils.translation import ugettext_lazy as _


class Person(AbstractUser, Votable):
    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'
    GENDER_CHOICES = (
        (GENDER_MALE, _('Male')),
        (GENDER_FEMALE, _('Female'))
    )

    karma = models.IntegerField(db_index=True, default=0, blank=True)
    avatar = models.ImageField(upload_to=settings.UPLOAD_AVATAR_DIR, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, db_index=True)

    contacts = models.ManyToManyField('self', verbose_name='contacts')
    guests = models.ManyToManyField('self', verbose_name='guests')
    language = models.CharField(choices=settings.LANGUAGES, max_length=5, default='ru', blank=True)

    confirmation = models.CharField(max_length=8, blank=True, null=True)
    verified = models.BooleanField(default=False, blank=True, db_index=True)
    register_date = models.DateTimeField(auto_created=True, blank=True, null=True)

    @property
    def new_contacts(self):
        return self.contacts.order_by('-id')[:9]

    @property
    def new_guests(self):
        return self.guests.order_by('-id')[:9]

    @property
    def publics(self):
        from public.models import Public
        return Public.objects.filter(owner=self)

    @property
    def followed(self):
        from public.models import Public
        return Public.objects.filter(members__in=[self])

    @property
    def image(self):
        if not self.avatar:
            return static('media/noavatar.jpg')
        return '/{}'.format(self.avatar.url)

    def save(self, *args, **kwargs):
        if not self.verified:
            self.confirmation = Encrypt(self.username).sha512.upper()[0:8]
        return super(Person, self).save(*args, **kwargs)

    def verify(self):
        self.verified = True
        self.confirmation = None
        return self.save()

person/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
from django import forms
from person.models import Person
from django.utils.translation import ugettext as _
from vile.service import TemplateEmail, absreverse


class UpdateAvatarForm(forms.ModelForm):
    def __init__(self, target=None, *args, **kwargs):
        super(UpdateAvatarForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Person
        fields = ['avatar']


class RegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=64, required=True)
    last_name = forms.CharField(max_length=64, required=True)
    username = forms.CharField(max_length=24, required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())
    password1 = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        uname = self.data['username'].strip()
        if len(uname) > 24:
            raise forms.ValidationError(_('Username is too long. Please choose username between 4 and 24 characters'))

        if re.match(ur'/[^A-Z0-9\_А-Я]/', uname, re.IGNORECASE):
            raise forms.ValidationError(_('Username contains illegal characters. Only A-Z, 0-9 and _ are allowed'))

        if Person.objects.filter(username=uname).count() > 0:
            raise forms.ValidationError(_('Username already used by another user'))

        return uname

    def clean_password(self):
        if self.data['password'] != self.data['password1']:
            raise forms.ValidationError(_('Passwords does not match'))

        return self.data['password']

    def save(self):
        data = self.cleaned_data
        person = Person(
            first_name=data['first_name'],
            last_name=data['last_name'],
            username=data['username'],
            email=data['email']
        )

        person.set_password(data['password'])
        person.save()

        # Send confirmation email
        TemplateEmail(
            subject='Registration',
            from_email='cods.max@gmail.com',
            to_emails=person.email,
            template='email/confirmation_email.html',
            context={
                'user': person,
                'activation_link': absreverse('person:confirmation', kwargs={'key': person.confirmation})
            }
        ).send()

        return person

person/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from person.forms import UpdateAvatarForm, RegistrationForm
from person.models import Person


def login_page(request):
    errors = []
    if request.GET.get('err') == '1':
        errors.append('Wrong username or password')

    if not request.user.is_anonymous():
        return redirect(
            reverse('home')
        )

    return render(request, 'person/login.html', {
        'message': errors
    })


def authorize(request):
    user = authenticate(
        username=request.POST.get('username'),
        password=request.POST.get('password')
    )

    if user is not None and user.is_active:
        login(request, user)
        return redirect(reverse('home'))
    return redirect(reverse('person:login') + '?err=1')


@login_required
def out(request):
    logout(request)
    return redirect(reverse('home'))


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            person = authenticate(
                username=request.POST.get('username'),
                password=request.POST.get('password')
            )

            login(request, user=person)
            return redirect(
                reverse('home')
            )
    else:
        form = RegistrationForm()

    return render(request, 'person/registration.html', {
        'form': form,
    })


def confirmation(request, key):
    user = Person.objects.filter(confirmation__iexact=key).first()

    if user:
        user.verify()

        return redirect(
            reverse('person:profile', kwargs={'username': user.username})
        )

    return redirect(reverse('home'))


def profile(request, username):
    user_profile = None
    try:
        user_profile = Person.objects.get(username=username)
    except:
        pass

    if not user_profile:
        return redirect(
            reverse('404')
        )

    is_current = request.user.pk == user_profile.pk
    is_friend = user_profile.contacts.filter(id=request.user.pk).count() > 0

    return render(request, 'person/profile.html', {
        'profile': user_profile,
        'is_friend': is_friend,
        'is_current': is_current
    })


def avatar(request):
    if request.method == 'POST':
        form = UpdateAvatarForm(
            data=request.POST,
            files=request.FILES,
            instance=request.user
        )

        if form.is_valid():
            form.save()
            return redirect(reverse('person:avatar'))
    form = UpdateAvatarForm()
    return render(request, 'person/change_avatar.html', {
        'form': form
    })

templates/person/change_avatar.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}
    <form action="" id="avatar-form" method="post" enctype="multipart/form-data" class="block html-form tab flat">
        {% csrf_token %}

        <header class="title">{% trans 'Upload New Profile Image' %}</header>
        <p>{{ form.non_field_errors }}</p>
        
        <div class="input avatar">
            {% if user.avatar %}
                <img src="{{ user.image }}" alt="{{ user.username }}">
            {% else %}
                <img src="{% static 'media/noavatar.jpg' %}" alt="{{ user.username }}">
            {% endif %}
        </div>
        <div class="input {% if form.errors.title %}invalid{% endif %}">
            {{ form.avatar }}
        </div>
        <div class="action">
            <button class="btn flat" type="submit">{% trans 'Upload' %}</button>
        </div>
    </form>
{% endblock content %}

templates/person/login.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block rside %}{% endblock %}
{% block content %}
    <div class="headed wide html-form block divided float-rt">
        <header class="block-title">Authorization</header>
        <section class="block-body">
            {% for msg in message %}
                <p class="warning">{{ msg }}</p>
            {% endfor %}
            <form action="{% url 'person:auth' %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <input type="text" name="username" placeholder="{% trans 'Email or Login' %}">
                </div>
                <div class="input">
                    <input type="password" name="password" placeholder="{% trans 'Password' %}">
                </div>
                <input type="submit" class="btn" value="{% trans 'Login' %}">
            </form>
        </section>
    </div>
{% endblock content %}

templates/person/profile-bar.html
{% load i18n %}
{% if not user.is_authenticated %}
    <div class="headed wide html-form block">
        <header class="block-title">{% trans 'Authorization' %}</header>
        <section class="block-body navbar">
            <form action="{% url 'person:auth' %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <input type="text" name="username" placeholder="{% trans 'Email or Login' %}">
                </div>
                <div class="input">
                    <input type="password" name="password" placeholder="{% trans 'Password' %}">
                </div>
                <input type="submit" class="btn" value="{% trans 'Login' %}">
                <a style="text-align: center;" href="{% url 'person:register' %}">{% trans 'Create new account' %}</a>
            </form>
        </section>
    </div>
{% else %}
    <div class="headed wide html-form block">
        <header class="block-title">{% trans 'Author Karma' %} <span class="float-rt">{{ user.karma }}</span></header>
        <section class="block-body navbar">
            {% for club in my_clubs %}
                <a href="{% url 'club:home' club.id %}" class="block-block">{{ club.title }}</a>
            {% endfor %}

            <br>
            {% if user.verified %}
            <a href="{% url 'club:create' %}" class="btn">{% trans 'Create New Club' %}</a>
            {% else %}
                <a href="">{% trans 'Verify Email Address' %}</a>
            {% endif %}
        </section>
    </div>
{% endif %}

templates/person/profile-rside.html
{% load i18n %}
<!-- Profile control -->
<div class="headed block">
    <header class="block-title">
        {% if not profile.first_name or not profile.last_name %}
            {{ profile.username }}
        {% else %}
            {{ profile.first_name }} ({{ profile.username }}) {{ profile.last_name }}
        {% endif %}
        <span class="float-rt">{{ profile.karma }}</span>
    </header>
    <section class="block-body navbar">
        <img src="{{ profile.image }}" alt="{{ profile.username }}">
        {% if is_current %}
            <a href="">Settings</a>
        {% else %}
            {% if is_friend %}
                <a href="">{% trans 'Add to friends' %}</a>
            {% else %}
                <a href="">{% trans 'Remove from friends' %}</a>
            {% endif %}
        {% endif %}
    </section>
</div>

<!-- Authored list -->
{% if profile.publics.all.count > 0 %}
<div class="headed block">
    <header class="block-title">
        {% trans 'Own club' %}
        <span class="float-rt">{{ profile.publics.all.count }}</span>
    </header>
    <section class="block-body navbar">
        {% for club in profile.publics.all %}
            <a href="{% url 'club:home' club.pk %}">{{ club.title }}</a>
        {% endfor %}
    </section>
</div>
{% endif %}

<!-- Followed list -->
{% if profile.followed.all.count > 0 %}
<div class="headed block">
    <header class="block-title">
        {% trans 'Followed' %}
        <span class="float-rt">{{ profile.followed.all.count }}</span>
    </header>
    <section class="block-body navbar">
        {% for club in profile.followed.all %}
            <a href="{% url 'club:home' club.pk %}">{{ club.title }}</a>
        {% endfor %}
    </section>
</div>
{% endif %}

<!-- Friends list -->
<div class="headed block">
    <header class="block-title">
        {% trans 'Contacts' %}
        <span class="float-rt">{{ profile.contacts.all.count }}</span>
    </header>
    <section class="block-body persons-tab">
        {% for person in profile.new_contacts %}
            <div class="person-item">
                <img src="{{ person.image }}" alt="{{ person.username }}">
                <span>{{ person.username }}</span>
            </div>
        {% empty %}
            <div class="empty">{% trans 'No friends yet' %}</div>
        {% endfor %}
    </section>
</div>

<!-- Guests list -->
<div class="headed block">
    <header class="block-title">
        {% trans 'Guests' %}
        <span class="float-rt">{{ profile.guests.all.count }}</span>
    </header>
    <section class="block-body persons-tab">
        {% for person in profile.new_guests %}
            <div class="person-item">
                <img src="{{ person.image }}" alt="{{ person.username }}">
                <span>{{ person.username }}</span>
            </div>
        {% empty %}
            <div class="empty">{% trans 'No guests yet' %}</div>
        {% endfor %}
    </section>
</div>

templates/person/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block extra_title %}
    {% trans 'Profile' %}
    {% if not profile.first_name or not profile.last_name %}
        {{ profile.username }}
    {% else %}
        {{ profile.first_name }} ({{ profile.username }}) {{ profile.last_name }}
    {% endif %}
    |
{% endblock %}

{% block content %}
    <p class="empty">{% trans 'No messages found' %}</p>
{% endblock %}

{% block rside %}
    {% include 'person/profile-rside.html' %}
{% endblock %}

templates/person/registration.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}


{% block content %}
        <form action="" id="create-form" method="post" enctype="multipart/form-data" class="block html-form tab flat">
        {% csrf_token %}

        <header class="title">{% trans 'Registration new account' %}</header>
        {% if form.non_field_errors %}
        <p class="warning">{{ form.non_field_errors }}</p>
        {% endif %}

        <div class="input {% if form.errors.first_name %}invalid{% endif %}">
            <label for="id_first_name" class="table">{% trans 'First Name' %}</label>
            {{ form.first_name }}
        </div>
        {% if form.errors.first_name %}
            <div class="warning list">{{ form.errors.first_name }}</div>
        {% endif %}

        <div class="input {% if form.errors.last_name %}invalid{% endif %}">
            <label for="id_last_name" class="table">{% trans 'Last Name' %}</label>
            {{ form.last_name }}
        </div>
        {% if form.errors.last_name %}
            <div class="warning list">{{ form.errors.last_name }}</div>
        {% endif %}

        <div class="input {% if form.errors.email %}invalid{% endif %}">
            <label for="id_email" class="table">{% trans 'E-Mail Address' %}</label>
            {{ form.email }}
        </div>
        {% if form.errors.email %}
            <div class="warning list">{{ form.errors.email }}</div>
        {% endif %}

        <div class="input {% if form.errors.username %}invalid{% endif %}">
            <label for="id_username" class="table">{% trans 'Username (nick)' %}</label>
            {{ form.username }}
        </div>
        {% if form.errors.username %}
            <div class="warning list">{{ form.errors.username }}</div>
        {% endif %}

        <div class="input {% if form.errors.password %}invalid{% endif %}">
            <label for="id_password" class="table">{% trans 'Password' %}</label>
            {{ form.password }}
        </div>
        {% if form.errors.password %}
            <div class="warning list">{{ form.errors.password }}</div>
        {% endif %}

        <div class="input {% if form.errors.password %}invalid{% endif %}">
            <label for="id_password1" class="table">{% trans 'Repeat Password' %}</label>
            {{ form.password1 }}
        </div>
        {% if form.errors.password1 %}
            <div class="warning list">{{ form.errors.password1 }}</div>
        {% endif %}

        <div class="action">
            <button class="btn flat" type="submit">{% trans 'Register' %}</button>
        </div>
    </form>
{% endblock %}